// Generated by gencpp from file test1/mysrv.msg
// DO NOT EDIT!


#ifndef TEST1_MESSAGE_MYSRV_H
#define TEST1_MESSAGE_MYSRV_H

#include <ros/service_traits.h>


#include <test1/mysrvRequest.h>
#include <test1/mysrvResponse.h>


namespace test1
{

struct mysrv
{

typedef mysrvRequest Request;
typedef mysrvResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct mysrv
} // namespace test1


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::test1::mysrv > {
  static const char* value()
  {
    return "a90b140ab03fe21a95df581c56fb33ea";
  }

  static const char* value(const ::test1::mysrv&) { return value(); }
};

template<>
struct DataType< ::test1::mysrv > {
  static const char* value()
  {
    return "test1/mysrv";
  }

  static const char* value(const ::test1::mysrv&) { return value(); }
};


// service_traits::MD5Sum< ::test1::mysrvRequest> should match 
// service_traits::MD5Sum< ::test1::mysrv > 
template<>
struct MD5Sum< ::test1::mysrvRequest>
{
  static const char* value()
  {
    return MD5Sum< ::test1::mysrv >::value();
  }
  static const char* value(const ::test1::mysrvRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::test1::mysrvRequest> should match 
// service_traits::DataType< ::test1::mysrv > 
template<>
struct DataType< ::test1::mysrvRequest>
{
  static const char* value()
  {
    return DataType< ::test1::mysrv >::value();
  }
  static const char* value(const ::test1::mysrvRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::test1::mysrvResponse> should match 
// service_traits::MD5Sum< ::test1::mysrv > 
template<>
struct MD5Sum< ::test1::mysrvResponse>
{
  static const char* value()
  {
    return MD5Sum< ::test1::mysrv >::value();
  }
  static const char* value(const ::test1::mysrvResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::test1::mysrvResponse> should match 
// service_traits::DataType< ::test1::mysrv > 
template<>
struct DataType< ::test1::mysrvResponse>
{
  static const char* value()
  {
    return DataType< ::test1::mysrv >::value();
  }
  static const char* value(const ::test1::mysrvResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // TEST1_MESSAGE_MYSRV_H
