// Generated by gencpp from file test1/mysrvRequest.msg
// DO NOT EDIT!


#ifndef TEST1_MESSAGE_MYSRVREQUEST_H
#define TEST1_MESSAGE_MYSRVREQUEST_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace test1
{
template <class ContainerAllocator>
struct mysrvRequest_
{
  typedef mysrvRequest_<ContainerAllocator> Type;

  mysrvRequest_()
    : a(0)
    , b(0)
    , c(0)  {
    }
  mysrvRequest_(const ContainerAllocator& _alloc)
    : a(0)
    , b(0)
    , c(0)  {
  (void)_alloc;
    }



   typedef int32_t _a_type;
  _a_type a;

   typedef int32_t _b_type;
  _b_type b;

   typedef int32_t _c_type;
  _c_type c;





  typedef boost::shared_ptr< ::test1::mysrvRequest_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::test1::mysrvRequest_<ContainerAllocator> const> ConstPtr;

}; // struct mysrvRequest_

typedef ::test1::mysrvRequest_<std::allocator<void> > mysrvRequest;

typedef boost::shared_ptr< ::test1::mysrvRequest > mysrvRequestPtr;
typedef boost::shared_ptr< ::test1::mysrvRequest const> mysrvRequestConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::test1::mysrvRequest_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::test1::mysrvRequest_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace test1

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': True, 'IsMessage': True, 'HasHeader': False}
// {'test1': ['/home/fjj/documents/fjj_ros_code/fjj_test_code/src/test1/msg'], 'std_msgs': ['/opt/ros/kinetic/share/std_msgs/cmake/../msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::test1::mysrvRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::test1::mysrvRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::test1::mysrvRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::test1::mysrvRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::test1::mysrvRequest_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::test1::mysrvRequest_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::test1::mysrvRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "c8e8991925bcc343091e9b8015dc05ec";
  }

  static const char* value(const ::test1::mysrvRequest_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xc8e8991925bcc343ULL;
  static const uint64_t static_value2 = 0x091e9b8015dc05ecULL;
};

template<class ContainerAllocator>
struct DataType< ::test1::mysrvRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "test1/mysrvRequest";
  }

  static const char* value(const ::test1::mysrvRequest_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::test1::mysrvRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "int32 a\n\
int32 b\n\
int32 c\n\
";
  }

  static const char* value(const ::test1::mysrvRequest_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::test1::mysrvRequest_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.a);
      stream.next(m.b);
      stream.next(m.c);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct mysrvRequest_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::test1::mysrvRequest_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::test1::mysrvRequest_<ContainerAllocator>& v)
  {
    s << indent << "a: ";
    Printer<int32_t>::stream(s, indent + "  ", v.a);
    s << indent << "b: ";
    Printer<int32_t>::stream(s, indent + "  ", v.b);
    s << indent << "c: ";
    Printer<int32_t>::stream(s, indent + "  ", v.c);
  }
};

} // namespace message_operations
} // namespace ros

#endif // TEST1_MESSAGE_MYSRVREQUEST_H
