// Generated by gencpp from file msg_demo/srv_demoResponse.msg
// DO NOT EDIT!


#ifndef MSG_DEMO_MESSAGE_SRV_DEMORESPONSE_H
#define MSG_DEMO_MESSAGE_SRV_DEMORESPONSE_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace msg_demo
{
template <class ContainerAllocator>
struct srv_demoResponse_
{
  typedef srv_demoResponse_<ContainerAllocator> Type;

  srv_demoResponse_()
    : sum(0)  {
    }
  srv_demoResponse_(const ContainerAllocator& _alloc)
    : sum(0)  {
  (void)_alloc;
    }



   typedef int64_t _sum_type;
  _sum_type sum;





  typedef boost::shared_ptr< ::msg_demo::srv_demoResponse_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::msg_demo::srv_demoResponse_<ContainerAllocator> const> ConstPtr;

}; // struct srv_demoResponse_

typedef ::msg_demo::srv_demoResponse_<std::allocator<void> > srv_demoResponse;

typedef boost::shared_ptr< ::msg_demo::srv_demoResponse > srv_demoResponsePtr;
typedef boost::shared_ptr< ::msg_demo::srv_demoResponse const> srv_demoResponseConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::msg_demo::srv_demoResponse_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::msg_demo::srv_demoResponse_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace msg_demo

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': True, 'IsMessage': True, 'HasHeader': False}
// {'std_msgs': ['/opt/ros/kinetic/share/std_msgs/cmake/../msg'], 'msg_demo': ['/home/fjj/documents/fjj_ros_code/fjj_code/src/msg_demo/msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::msg_demo::srv_demoResponse_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::msg_demo::srv_demoResponse_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::msg_demo::srv_demoResponse_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::msg_demo::srv_demoResponse_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::msg_demo::srv_demoResponse_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::msg_demo::srv_demoResponse_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::msg_demo::srv_demoResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "b88405221c77b1878a3cbbfff53428d7";
  }

  static const char* value(const ::msg_demo::srv_demoResponse_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xb88405221c77b187ULL;
  static const uint64_t static_value2 = 0x8a3cbbfff53428d7ULL;
};

template<class ContainerAllocator>
struct DataType< ::msg_demo::srv_demoResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "msg_demo/srv_demoResponse";
  }

  static const char* value(const ::msg_demo::srv_demoResponse_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::msg_demo::srv_demoResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "int64 sum\n\
\n\
";
  }

  static const char* value(const ::msg_demo::srv_demoResponse_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::msg_demo::srv_demoResponse_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.sum);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct srv_demoResponse_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::msg_demo::srv_demoResponse_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::msg_demo::srv_demoResponse_<ContainerAllocator>& v)
  {
    s << indent << "sum: ";
    Printer<int64_t>::stream(s, indent + "  ", v.sum);
  }
};

} // namespace message_operations
} // namespace ros

#endif // MSG_DEMO_MESSAGE_SRV_DEMORESPONSE_H
